
var hosts = [
    { name: "netflix", url: "netflix.com" },
    { name: "facebook", url: "facebook.com" },
    { name: "youtube", url: "youtube.com" },
    { name: "yahoo", url: "yahoo.com" },
    { name: "yahoo mail", url: "mail.yahoo.com" },
    { name: "google", url: "google.com" },
    { name: "outlook", url: "outlook.com" },
    { name: "steam", url: "steampowered.com" },
    { name: "whatsapp", url: "whatsapp.com" },
    { name: "windows live", url: "live.com" },
    { name: "instagram", url: "instagr.am" },
    { name: "gmail", url: "mail.google.com"},
    { name: "dropbox", url: "dropbox.com"},
    { name: "battlenet", url: "battle.net" },
    { name: "reddit", url: "reddit.com" },
    { name: "fanfiction", url: "fanfiction.net" },
    { name: "amazon", url: "amazon.com" },
    { name: "pinterest", url: "pinterest.com" },
    { name: "twitter", url: "twitter.com"},
    { name: "tumblr", url: "tumblr.com" },
    { name: "xbox", url: "xbox.com" },
    { name: "aol", url: "aol.com" },
    { name: "minecraft", url: "minecraft.net" },
    { name: "comcast", url: "comcast.com"},
    { name: "pandora", url: "pandora.com"},
    { name: "omegle", url: "omegle.com" },
    { name: "paypal", url: "paypal.com"},
    { name: "craigslist", url: "craigslist.org" },
    { name: "google drive", url: "drive.google.com"},
    { name: "steam community", url: "steamcommunity.com" },
    { name: "hulu", url: "hulu.com"},
    { name: "twitch", url: "twitch.tv" },
    { name: "ubisoft", url: "ubisoft.com" },
    { name: "github", url: "github.com" },
    { name: "der standard", url: "derstandard.at" },
    { name: "bitbucket", url: "bitbucket.org" },
    { name: "test", url: "httpstat.us/503" }
]

module.exports = hosts;